version: '3.8'

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: islamwiki_libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_HOST=0.0.0.0
      - LT_PORT=5000
      - LT_API_KEYS=false
      - LT_DISABLE_WEB_UI=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
